
export const postPhotoTypes = [{"id":10001,"route":"wedding","title":"Fotografia de bodas", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"https://jangweddingphotography.com/wp-content/uploads/2019/10/monet-malatino-wedding-thumb-768x512.jpg"},
{"id":10002,"route":"aerial","title":"Fotografia aerea", "description":"Po sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Quadcopter_camera_drone_in_flight.jpg/800px-Quadcopter_camera_drone_in_flight.jpg"},
{"id":10003,"route":"models","title":"Fotografia modelos", "description": "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "post_image":"https://e.rpp-noticias.io/normal/2016/02/02/052605_73326.jpg"} ,
{"id":10004,"route":"food","title":"Fotografia de alimentos","description":"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ", "post_image":"https://eatforum.org/content/uploads/2018/05/table_with_food_top_view_900x700.jpg"}
];


export const postsAerial = [{"id":30001,"route":"wedding","title":"Aerial Post 1", "description": "Loremm ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"https://qph.fs.quoracdn.net/main-qimg-6df3990d3c18056136f384598d9bd2c6"},
{"id":30002,"route":"aerial","title":"Aerial Post 2", "description":"Po sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"https://lh5.googleusercontent.com/proxy/e1DI8emxgxDXE1S3adCqp71I6NJH95N-sOV0wxIPde9Lis7tF610msDewaw7qYi6plbxYZZFNiYZZON6API3Oa5TKrZi8IiIgdtLlmy8DkyppoBwhI8gKM3t-UuezjUg6qidWt8PwFZl1gTYRpLRV593A3Zj0x4OO9-r=s0-d"},
{"id":30003,"route":"model","title":"Aerial Post 3", "description": "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "post_image":"https://foto-spots.com/wp-content/uploads/2015/12/tomas-aereas-750x400.jpg"} ,
{"id":30004,"route":"food","title":"Aerial Post 4","description":"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ", "post_image":"https://pedrazaproducciones.com/thumbs/hotel-tequendama-bogota-vista-aerea-torre-colpatria-dia-001-c83eed346079d77a5700a809f8addab6.jpg"}
];

export const postsFood = [{"id":20001,"route":"wedding","title":"Food photography post 1", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"food1.jpg"},
{"id":20002,"route":"aerial","title":"Food photography post 2", "description":"Po sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"food2.jpg"},
{"id":20003,"route":"model","title":"Food photography post 3", "description": "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "post_image":"food3.jpg"} ,
{"id":20004,"route":"food","title":"Food photography post 4","description":"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ", "post_image":"food4.jpg"}
];

export const postsWedding = [{"id":40001,"route":"wedding","title":"Wedding photography post 1", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"https://d25tv1xepz39hi.cloudfront.net/2019-01-16/files/wedding-photography_1803.jpg"},
{"id":40002,"route":"aerial","title":"Wedding photography post 2", "description":"Po sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"https://d25tv1xepz39hi.cloudfront.net/2019-01-16/files/wedding-photography_1803-5.jpg"},
{"id":40003,"route":"model","title":"Wedding photography post 3", "description": "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "post_image":"https://d25tv1xepz39hi.cloudfront.net/2019-01-16/files/wedding-photography_1803-6.jpg"} ,
{"id":40004,"route":"food","title":"Wedding photography post 4","description":"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ", "post_image":"https://d25tv1xepz39hi.cloudfront.net/2016-05-16/files/Raymond3.jpg"}
];

export const postsModels = [{"id":50001, "route":"wedding","title":"Model Post 1", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"model1.jpg"},
{"id":500011, "route":"aerial","title":"Model Post 2", "description":"Po sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"model2.jpg"},
{"id":500012, "route":"model","title":"Model Post 3", "description": "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "post_image":"model4.jpg"} ,
{"id":500013, "route":"food","title":"Model Post 4","description":"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ", "post_image":"model3.jpg"},
{"id":500014, "route":"wedding","title":"Model Post 1", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"model1.jpg"},
{"id":500015, "route":"aerial","title":"Model Post 2", "description":"Po sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"model2.jpg"},
{"id":500011, "route":"model","title":"Model Post 3", "description": "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "post_image":"model4.jpg"} ,
{"id":500061, "route":"food","title":"Model Post 4","description":"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ", "post_image":"model3.jpg"},
{"id":500031, "route":"wedding","title":"Model Post 1", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"model1.jpg"},
{"id":500041, "route":"aerial","title":"Model Post 2", "description":"Po sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"model2.jpg"},
{"id":500051, "route":"model","title":"Model Post 3", "description": "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "post_image":"model4.jpg"} ,
{"id":500061, "route":"food","title":"Model Post 4","description":"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ", "post_image":"model3.jpg"},
{"id":500071, "route":"wedding","title":"Model Post 1", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"model1.jpg"},
{"id":500081, "route":"aerial","title":"Model Post 2", "description":"Po sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"model2.jpg"},
{"id":500091, "route":"model","title":"Model Post 3", "description": "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "post_image":"model4.jpg"} ,
{"id":500001, "route":"food","title":"Model Post 4","description":"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ", "post_image":"model3.jpg"},
{"id":502001, "route":"wedding","title":"Model Post 1", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"model1.jpg"},
{"id":50401, "route":"aerial","title":"Model Post 2", "description":"Po sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"model2.jpg"},
{"id":50501, "route":"model","title":"Model Post 3", "description": "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "post_image":"model4.jpg"} ,
{"id":57001, "route":"food","title":"Model Post 4","description":"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ", "post_image":"model3.jpg"},
{"id":508001, "route":"wedding","title":"Model Post 1", "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"model1.jpg"},
{"id":50901, "route":"aerial","title":"Model Post 2", "description":"Po sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi", "post_image":"model2.jpg"},
{"id":52001, "route":"model","title":"Model Post 3", "description": "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", "post_image":"model4.jpg"} ,
{"id":53001, "route":"food","title":"Model Post 4","description":"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ", "post_image":"model3.jpg"}
];
